### ISSUE TITLE
Live view does not work in 2.91

### ISSUE THREAD

**Issue by GottfriedHofmann** [Looking-Glass/blenderLKG#15]
When using live view in 2.91, it shows a weirdly scrambled result that seems to show the scene always from the same angle.

**Comment by GottfriedHofmann** [comment]
It seems like it only manages to copy the first view to the quilt, all the others are black.
Issue persists in 2.92 beta.

**Comment by GottfriedHofmann** [comment]
There are also problems with the Multiview system at the moment: https://developer.blender.org/T84398

**Comment by GottfriedHofmann** [comment]
I have created a simple demo script and file and submitted a bug report: https://developer.blender.org/T84402

**Comment by regcs** [comment]
For the second bug, you can use the following as workaround in case the fixing takes longer:

https://developer.blender.org/T84402#1087183

**Comment by GottfriedHofmann** [comment]
> 
> 
> For the second bug, you can use the following as workaround in case the fixing takes longer:
> 
> https://developer.blender.org/T84402#1087183

Fortunately this is how we did things in the past which means the infrastructure is already there: https://github.com/Looking-Glass/blenderLKG/commit/e4be3d1ac2eeb25906507c6379bb90f91d8477d4

**Comment by GottfriedHofmann** [comment]
Closed by https://github.com/Looking-Glass/blenderLKG/releases/tag/2.0-beta.4 - thank you for the help with the workaround.
