### ISSUE TITLE
blender portable "no connected LKG devices"

### ISSUE THREAD

**Issue by EasyIP2023** [Looking-Glass/blenderLKG#24]
When using the portable version of blender, if one saves their work, then re-open saved worked after leaving blender. It seems to not detect any new looking glasses. They way I solved it was by going to edit -> preferences -> add-ons. Removed the add-on then reinstalled it.

**Comment by psql** [comment]
I had this same issue on `2.92.0` for mac btw. Same solve as mentioned by @EasyIP2023
