### ISSUE TITLE
fails to render to non portrait looking glass display

### ISSUE THREAD

**Issue by BryanChrisBrown** [Looking-Glass/blenderLKG#38]
When clicking the send to quilt button with a Looking Glass 15.6" connected I get the following error: 

![image](https://user-images.githubusercontent.com/22871421/117986735-e00ca480-b307-11eb-9076-b789bff79c92.png)

**Comment by GottfriedHofmann** [comment]
Hello Bryan, have you tried version 3.0 alpha1 ? https://github.com/Looking-Glass/blenderLKG/releases/tag/3.0alpha1
Said error should be fixed there.

**Comment by alxdncn** [comment]
This should be resolved in version 3.0.1
