### ISSUE TITLE
Send quilt command python error

### ISSUE THREAD

**Issue by RocketCorgi** [Looking-Glass/blenderLKG#40]
Blender 2.93
Created a very basic setup using the "create render setup" with a single object inside the multiview box and then rendering.
Select the render result and execute the "send quilt command"

Python Error:
Python: Traceback (most recent call last):
  File "C:\Users\mac_j\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\looking_glass_tools\looking_glass_live_view.py", line 924, in execute
    quilt = od.create_quilt_from_holoplay_multiview_image(od, context)
  File "C:\Users\mac_j\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\looking_glass_tools\looking_glass_live_view.py", line 542, in create_quilt_from_holoplay_multiview_image
    img_str = multiview_image_path_split[0] + '.' + str(i).zfill(2) + '.' + multiview_image_path_split[2]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by GottfriedHofmann** [comment]
Unfortunately sending rendered images directly to Holoplay Service without saving them to disk first is not supported yet (that would require two changes to Blender core where our hands are tied). But I have added a warning when the user tries to send either the Render Result or Viewer Node image datablocks in https://github.com/Looking-Glass/blenderLKG/commit/77145cddce1997ebe83274439e128b39f725f2b6.
